### PR TITLE
Added 11.8 to version select

### PR DESCRIPTION
**Pull request by deadphoenix8091**
Would be awesome if you could merge this pr.
We get alot of confused users while assisting with hax methods and this would definetly save us alot of trouble. 

Thanks in advance.

### CODE REVIEW

**Comment by smealum** [comment]
has this been tested? specifically did you make sure you get the right payload on 11.8 with this change?

**Comment by deadphoenix8091** [comment]
Yes, I verified it works and serves the same payload as it does for 11.7. 
Tested with all regions. 

(It only needs this single line change because 11.7 is your else case everywhere)

**Comment by deadphoenix8091** [comment]
If you would like to verify this for yourself, my fork is accessible here: 
https://deadphoenix8091.github.io/3ds/

**Comment by smealum** [comment]
thanks for this, sorry i've been so lazy

**Pull request merged**
